### ISSUE TITLE
Updating an icon generates a double .desktop entry in slingshot

### ISSUE THREAD

**Issue by Alecaddd** [donadigo/appeditor#44] opened 2018-03-13 23:16 UTC
I updated Sublime Text by adding a slightly smaller icon that respects the sizing of native elementary os icons.
After doing that, I started getting a duplicated result while searching for the app in slingshot.

The duplication doesn't appear in the regular app drawer, only on search.

![app-editor](https://user-images.githubusercontent.com/2527103/37374709-950b3626-26d9-11e8-8b05-a84a1039e56b.png)

**Comment by gcjuan** [comment] 2019-02-13 14:35
The same applies for me on eOS Loki.
I've modified some entry names in order it to be more clear on the screenshot.

I'm gonna try it on eOS Juno on a VM to see (and maybe discard) if it's really an app issue or rather a problem on the Slingshots' search mechanism.

![imagen](https://user-images.githubusercontent.com/19599325/52718623-33b2ab00-2fa4-11e9-9596-7ed419543e8f.png)

**Comment by gcjuan** [comment] 2019-02-13 16:20
Confirmed! I've tried to reproduce it on elementary OS Juno 5.0 and the issue isn't there anymore, no more duplicated entries.

**The problem seems no to be AppEditor but the Applications Menu** (aka Slingshot).
On elementary OS Loki 0.4 the Slingshots' latest version is 2.2.0. On Juno, it was updated (I actually have tested it having version 2.4.2, the currently [latest release](https://github.com/elementary/applications-menu/releases)).

You can check your installed Slingshot version under _/usr/share/doc/slingshot-launcher/_ opening the file _changelog.Debian.gz_. (`man slingshot-launcher` says, the version should be returned with `slingshot-launcher -v` but it doesn't).

It was fixed on Slingshot 2.3.0. You can see here the [list of fixes for that version](https://github.com/elementary/applications-menu/issues?q=is%3Aclosed+milestone%3A2.3.0).

Here there is the [reported issue](https://github.com/elementary/applications-menu/issues/7) and here the[ corresponding fix](https://github.com/elementary/applications-menu/pull/58).

On the following screenshot I changed the AppEditor's icon and text on elementary OS Juno and here you got the result =)

![imagen](https://user-images.githubusercontent.com/19599325/52725088-cb1dfb00-2fb0-11e9-8b2e-a67e35418ebe.png)

**Closed** 2019-02-17 20:05 UTC
